spring.application.name=projeto
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cliniq}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:cliniq_app}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:cliniq_pass}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
